server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            #- After=2020-10-18T10:38:37.692+08:00[Asia/Shanghai]
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #- Cookie=username, oy
            #- Header=X-Request-Id, \d+ #请求头要有 X-Request-Id的属性并且只为整数的正则表达式
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:   #服务提供者provider注册进eureka服务列表中
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone:  http://eureka7001.com:7001/eureka